name: notecraft-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - python-dotenv
  - pillow
  - pymupdf
  - boto3
  - subprocess
  - os
  - concurrent